version: "3.8"

services:
  traefik:
    image: traefik:vacherin
    container_name: traefik
    ports:
      - "80:80"
      - "443:443"
      # - "8080:8080"
    networks:
      - shared

    # traefik
    command:
      # provider
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false

      # dashboard
      # - --api.dashboard=true
      # - --api.insecure=true

      # entry points
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443

      # Certificate
      - --certificatesresolvers.letsencrypt.acme.dnschallenge=true
      - --certificatesresolvers.letsencrypt.acme.dnschallenge.provider=cloudflare
      - --certificatesresolvers.letsencrypt.acme.email=${CA_EMAIL}
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
      - --certificatesresolvers.letsencrypt.acme.keyType=EC384

    labels:
      - traefik.enable=true

    # For Cloudflare auth
    environment:
      - CLOUDFLARE_EMAIL=${CF_EMAIL}
      - CLOUDFLARE_DNS_API_TOKEN=${CF_TOKEN}

    # environment
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # mandatory
      - ./letsencrypt:/letsencrypt

networks:
  shared:
    name: shared
