version: "3.8"

services:
  nginx-b:
    image: nginx:mainline-alpine
    container_name: nginx-b
    networks:
      - shared

    # traefik
    labels:
      - traefik.enable=true
      - traefik.docker.network=shared
      - traefik.http.routers.nginx-b.rule=Host(`test-b.${HOST}`)
      - traefik.http.routers.nginx-b.entrypoints=websecure
      - traefik.http.routers.nginx-b.tls.certresolver=letsencrypt

    # environment
    volumes:
      - ./html:/usr/share/nginx/html/

networks:
  shared:
    name: shared
